apiVersion : skaffold/v2alpha3
kind : Config
deploy : 
  kubectl : 
    manifests : 
      - ./infra/k8s/*
build : 
  local : 
    push : false # disable docker push by default
  artifacts : 
    - image : salikzquidz/auth
      context : auth # folder name which contain the auth
      docker : 
        dockerfile : Dockerfile
      sync : 
        manual : 
          - src : 'src/**/*.ts'
            dest : .